### ISSUE TITLE
Add a base Dockerfile for Shaarli

### ISSUE THREAD

**Issue by virtualtam** [shaarli/docker-shaarli#1]
## TODO
- [x] inherit from `debian:jessie`
- [x] packages
 - [x] curl
 - [x] nginx
 - [x] php5-fpm
 - [x] php5-gd
 - [x] supervisor
- [x] add nginx config
- [x] deploy Shaarli's `master` tarball to `/var/www/shaarli`
- [x] use a configurable volume for `/var/www/shaarli/data`
- [x] add supervisor config
- [x] manage services with supervisor
- [x] add zlib license

### Documentation
- http://blog.thoward37.me/articles/where-are-docker-images-stored/
- https://docs.docker.com/reference/builder/
- https://docs.docker.com/userguide/dockervolumes/
- https://docs.docker.com/articles/dockerfile_best-practices/
- https://docs.docker.com/articles/using_supervisord/
- http://nginx.org/en/docs/ngx_core_module.html#daemon
- http://supervisord.org/

### Shaarli configuration
- https://github.com/shaarli/Shaarli/wiki/Server-requirements
- https://github.com/shaarli/Shaarli/wiki/Server-configuration#nginx
- https://github.com/shaarli/Shaarli/wiki/Shaarli-configuration

### Dockerfiles
- https://github.com/eugeneware/docker-wordpress-nginx
- https://github.com/ngineered/nginx-php-fpm
